blueprint:
  name: Philips Hue Dimmer Switch (zigbee2mqtt integration)
  description: |
    Philips Hue Dimmer Switch:
    - 3 scene buttons (short press on/up/down)
    - brightness control (hold up/down)
    - off button (short press off)
  domain: automation
  author: Bart Schuurmans
  source_url: https://github.com/BartSchuurmans/home-assistant-config/blob/main/blueprints/hue-dimmer-switch-zigbee2mqtt.yaml
  homeassistant:
    min_version: "2024.10.0"
  input:
    z2m_device_name:
      name: Dimmer Switch Name
      description: "The friendly name of the Hue Dimmer Switch in Zigbee2MQTT"
      selector:
        text:
    z2m_base_topic:
      name: Zigbee2MQTT Base Topic
      description: "The MQTT base topic of Zigbee2MQTT"
      default: zigbee2mqtt
      selector:
        text:
    target_light:
      name: Target Lights
      description: "Target lights used for the off button and brightness control"
      selector:
        target:
          entity:
            - domain: light
    scene_on:
      name: On Button
      description: "Scene to set when pushing the On button"
      selector:
        entity:
          filter:
            - domain: scene
    scene_up:
      name: Up Button
      description: "Scene to set when pushing the Brightness Up button"
      selector:
        entity:
          filter:
            - domain: scene
    scene_down:
      name: Down Button
      description: "Scene to set when pushing the Brightness Down button"
      selector:
        entity:
          filter:
            - domain: scene
    brightness_step_pct:
      name: Brightness step size
      description: "Percentage of brightness to change per tick (~ second)"
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

mode: parallel

trigger_variables:
  z2m_base_topic: !input z2m_base_topic
  z2m_device_name: !input z2m_device_name

triggers:
  - trigger: mqtt
    topic: "{{ z2m_base_topic }}/{{ z2m_device_name }}/action"
    payload: "on_press_release"
    id: on_pressed
  - trigger: mqtt
    topic: "{{ z2m_base_topic }}/{{ z2m_device_name }}/action"
    payload: "up_press_release"
    id: up_pressed
  - trigger: mqtt
    topic: "{{ z2m_base_topic }}/{{ z2m_device_name }}/action"
    payload: "up_hold"
    id: up_tick
  - trigger: mqtt
    topic: "{{ z2m_base_topic }}/{{ z2m_device_name }}/action"
    payload: "down_press_release"
    id: down_pressed
  - trigger: mqtt
    topic: "{{ z2m_base_topic }}/{{ z2m_device_name }}/action"
    payload: "down_hold"
    id: down_tick
  - trigger: mqtt
    topic: "{{ z2m_base_topic }}/{{ z2m_device_name }}/action"
    payload: "off_press_release"
    id: off_pressed

variables:
  brightness_step_pct: !input brightness_step_pct

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: on_pressed
        sequence:
          - action: scene.turn_on
            target:
              entity_id: !input scene_on
            data:
              transition: 1
      - conditions:
          - condition: trigger
            id: up_pressed
        sequence:
          - action: scene.turn_on
            target:
              entity_id: !input scene_up
            data:
              transition: 1
      - conditions:
          - condition: trigger
            id: down_pressed
        sequence:
          - action: scene.turn_on
            target:
              entity_id: !input scene_down
            data:
              transition: 1
      - conditions:
          - condition: trigger
            id: up_tick
        sequence:
          - action: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: "{{ brightness_step_pct }}"
              transition: 1
      - conditions:
          - condition: trigger
            id: down_tick
        sequence:
          - action: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: "{{ -1 * brightness_step_pct }}"
              transition: 1
      - conditions:
          - condition: trigger
            id: off_pressed
        sequence:
          - action: light.turn_off
            target: !input target_light
            data:
              transition: 1
